In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('2021_feature_engineered.csv', index_col='Unnamed: 0')
data.head()

,date,average_kills_Bluetop,average_deaths_Bluetop,average_assists_Bluetop,average_cs_Bluetop,average_score_Bluetop,average_firstbloodkill_Bluetop,average_triplekills_Bluetop,average_quadrakills_Bluetop,average_pentakills_Bluetop,...,average_deaths_Redsup,average_assists_Redsup,average_cs_Redsup,average_score_Redsup,average_firstbloodkill_Redsup,average_triplekills_Redsup,average_quadrakills_Redsup,average_pentakills_Redsup,total_games_Redsup,score_Redsup
0,2021-01-09 09:22:04,-1.0,-1.0,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,0.0,14.72
1,2021-01-09 10:16:20,0.0,0.0,2.0,276.0,9.52,0.0,0.0,0.0,0.0,...,2.0,8.0,36.0,14.72,0.0,0.0,0.0,0.0,1.0,16.72
2,2021-01-09 11:30:25,-1.0,-1.0,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,0.0,19.64
3,2021-01-09 12:23:44,1.0,1.0,5.0,270.0,17.40,0.0,0.0,0.0,0.0,...,3.0,3.0,47.0,3.94,0.0,0.0,0.0,0.0,1.0,34.78
4,2021-01-09 13:19:06,0.0,3.0,4.5,280.0,11.60,0.0,0.0,0.0,0.0,...,2.5,5.0,41.0,12.82,0.0,0.0,0.0,0.0,2.0,23.90

In [11]:
data.groupby('date')[['average_kills_Bluetop']].count().sort_values(by='average_kills_Bluetop', ascending=False).head()

                     average_kills_Bluetop
date
2021-06-27 08:43:30                   1024
2021-06-16 12:06:52                   1024
2021-07-04 08:16:21                      1
2021-07-04 07:16:30                      1
2021-07-04 05:14:22                      1